package com.apigateway.managment.taskapigateway.dto;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.List;

@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@ApiModel(description="All details about the Gateway")
public class GatewayDTO implements Serializable {
    @ApiModelProperty(notes="the id most be an numeric autogenerated key")
    private Long id;

    @ApiModelProperty(notes="the id most be an numeric autogenerated key")
    private String serialNumber;

    @ApiModelProperty(notes="the id most be an numeric autogenerated key")
    private String name;

    @ApiModelProperty(notes="the id most be an numeric autogenerated key")
    private String ipAddress;

    @ApiModelProperty(notes="the id most be an numeric autogenerated key")
    private List<PeripheralDeviceDTO> peripheralDevices;

}
