package com.apigateway.managment.taskapigateway.dto;

import com.apigateway.managment.taskapigateway.utils.ResponseType;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@ApiModel(description="Details about the response to an unwanted event in the system.")
public class ResponseDTO {
    @ApiModelProperty(notes="the id most be an numeric autogenerated key")
    private ResponseType type;

    @ApiModelProperty(notes="the id most be an numeric autogenerated key")
    private String message;

    @ApiModelProperty(notes="the id most be an numeric autogenerated key")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy hh:mm:ss")
    private Date date;

}
