# Before building the docker image run:
#
# mvn package
#
# Then, build the image with:
#
# docker build -f dockerfile.jvm -t task-apigateway .
#
# Then run the container using:
#
# docker run -i --rm -p 8082:8082 task-apigateway:latest
#
###
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]