version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: 'gateways_db'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mynet
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      links:
        - db
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - '8080:80'
      volumes:
        - /sessions
      networks:
        - mynet
# Names our volume
volumes:
  my-db:
#    driver: local
networks:
  mynet:
#    driver: bridge